config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  as :user do
    get '/signup',    to: 'registrations#new'
    post '/signup',   to: 'registrations#create'
    get '/login',     to: 'devise/sessions#new'
    post '/login',    to: 'devise/sessions#create'
    delete '/logout', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    member do
      get :added_friends, :friend_requests
    end
  end
  resources :posts,       only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :likes,       only: [:create, :destroy]
  resources :comments,    only: [:create, :destroy]
  resources :profiles,    only: [:edit, :update]

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/license', to: 'static_pages#license'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
  # Like a post only once.
  validates_uniqueness_of :user_id, scope: [:post_id]
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    if @like.save
      flash[:success] = "Liked a post!"
    else
      flash[:danger] = "Cannot like a post more than once."
    end
    redirect_to request.referrer || root_url
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:post_id])
    @like.destroy
    flash[:success] = "Unliked a post."
    redirect_to request.referrer || root_url
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likes.html.erb
<% if current_user.likes.find_by(post_id: post.id) %>
  <%= link_to like_path(current_user, post_id: post.id, user_id: current_user.id),
                        method: :delete do %>
    <i class="fa fa-thumbs-o-down"></i>
  <% end %>
<% else %>
  <%= link_to likes_path(post_id: post.id, user_id: current_user.id),
                         method: :post do %>
    <i class="fa fa-thumbs-o-up"></i>
  <% end %>
<% end %>
<span class="badge">
  <% if post.liking_users.any? %>
    <%= post.liking_users.count %>
  <% end %>
</span>