config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  as :user do
    get '/signup',    to: 'registrations#new'
    post '/signup',   to: 'registrations#create'
    get '/login',     to: 'devise/sessions#new'
    post '/login',    to: 'devise/sessions#create'
    delete '/logout', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    member do
      get :added_friends, :friend_requests
    end
  end
  resources :posts,       only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :likes,       only: [:create, :destroy]
  resources :comments,    only: [:create, :destroy]
  resources :profiles,    only: [:edit, :update]

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/license', to: 'static_pages#license'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag :post_id, post.id %>
  <div class="media-body">
    <div class="form-group">
      <%= f.text_area :content, class: "form-control", rows: "1", placeholder: "Comment on this post!" %>
    </div>
  </div>
  <div class="media-right">
    <%= f.submit "Comment", class: "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <strong>
        This form contains <%= pluralize(object.errors.count, 'error') %>.
      </strong>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="posts">
    <%= render @feed_items %>
  </div>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create a Post!</h3>
  </div>
  <div class="panel-body">
    <%= form_for(@post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.text_area :content, class: "form-control", rows: "3", placeholder: "Inscribe me!" %>
      </div>
      <%= f.submit "Post", class: "btn btn-info" %>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="list-group">
  <%= link_to current_user do %>
    <%= gravatar_for(current_user, size: 16) %>
    <%= current_user.first_name %>
  <% end %>
  <%= link_to friend_requests_user_path(current_user) do %>
    <i class="fa fa-inbox"></i> Notifications
  <% end %>
  <%= link_to added_friends_user_path(current_user) do %>
    <i class="fa fa-users"></i> Friends
  <% end %>
  <%= link_to edit_user_registration_path do %>
    <i class="fa fa-gear"></i> Settings
  <% end %>
</div>