config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  as :user do
    get '/signup',    to: 'registrations#new'
    post '/signup',   to: 'registrations#create'
    get '/login',     to: 'devise/sessions#new'
    post '/login',    to: 'devise/sessions#create'
    delete '/logout', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    member do
      get :added_friends, :friend_requests
    end
  end
  resources :posts,       only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :likes,       only: [:create, :destroy]
  resources :comments,    only: [:create, :destroy]
  resources :profiles,    only: [:edit, :update]

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/license', to: 'static_pages#license'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "License", license_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "valhalla", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to current_user do %>
            <%= gravatar_for(current_user, size: 16) %>
            <%= current_user.first_name %>
          <% end %>
        </li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Find Friends", users_path %></li>
        <li>
          <%= link_to friend_requests_user_path(current_user) do %>
            <i class="fa fa-users"></i>
            <span class="badge">
              <% if current_user.pending_friends.count > 0 %>
                <%= current_user.pending_friends.count %>
              <% end %>
            </span>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Feed", root_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <%= link_to "Log In", login_path, class: "btn btn-default navbar-btn" %>
        <%= link_to "Sign Up", signup_path, class: "btn btn-default navbar-btn" %>
      <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>  
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>       
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>